:toc: left
:toclevels: 4
:toc-title: Desarrollo de Aplicaciones Moviles
:imagesdir: ./images
:stem: 
:stylesheet: daro-dark.css

= Desarrollo de Aplicaciones Moviles

== Semana 1



== Semana 2

=== PPT de clase sincronica

==== Etapas del Diseño

. *Diseño UX (Experiencia de Usuario)*
+
* Definición del flujo de navegación y estructura de la app.
* Creación de wireframes (bocetos de la interfaz sin detalles visuales).
* Priorización de la usabilidad y accesibilidad.

. *Diseño UI (Interfaz de Usuario) y Prototipado*
+
* Aplicación de colores, tipografías, iconos y estilo visual.
* Creación de prototipos interactivos con herramientas como Figma (que veremos más adelante) o Adobe XD.
* Diseño de elementos gráficos y animaciones.

. *Pruebas y Ajustes*
+
* Validación con usuarios para detectar problemas de usabilidad.
* Iteración y mejoras antes de pasar a desarrollo.

==== Diseño versus Prototipo

Diseñar una app es todo un desafío. Implica pensar su funcionalidad y darle una primera forma, a través de un prototipo, que permita evaluar ese diseño.

* El *diseño* supone pensar en la usabilidad, la accesibilidad y la experiencia de usuario.
* El *prototipado* es una herramienta esencial que permite visualizar y probar conceptos de diseño de manera interactiva antes de la implementación final.

Estos dos elementos forman un enfoque integral para optimizar la creación de aplicaciones, desde la conceptualización hasta la entrega, mejorando la calidad del producto y la experiencia del usuario.


==== Diseño UX

El diseño UX (User Experience o Experiencia de Usuario) es la disciplina que se encarga de agregar valor a la experiencia del usuario al utilizar nuestra aplicación. El objetivo es que esta experiencia sea significativa, relevante y placentera, y que dé un valor para el usuario. Dentro de User Experience hay diversas áreas de especialidad, una de ellas es el diseño de interfaces (UI).

El diseño de interfaces es un proceso iterativo y repetitivo en el que se va mejorando y optimizando constantemente, teniendo al usuario como centro de referencia y feedback. Es clave conocer sus necesidades, temores, objetivos y todo lo que nos pueda brindar información acerca de cómo y para qué usaría nuestra aplicación.


